language: ruby

sudo: required

services:
  - docker

install:
  - docker-compose build

before_script:
  - docker-compose up -d
  - docker-compose run blog bundle exec rake db:create
  - docker-compose run blog bundle exec rake db:migrate

script:
  - docker-compose run blog bundle exec rake