version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
    volumes:
      - postgres:/var/lib/postgresql/data

  blog:
    build: .
    volumes:
      - .:/blog
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: blog_user
      DATABASE_PASS: blog_pass
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres:
